### PR TITLE
Fix and handle new methods

### PR DESCRIPTION
**Pull request by cedbale**
- apply trickles to bufferize ICE candidates
- apply claim session to re-attach existing Janus session to the client
- fix legacy "listener" `ptype` to "subscriber"
- fix missing property to listenFeed
- add opaqueId notion

### CODE REVIEW

**Comment by hpherzog** [comment]
Thank you for your contribution. Will check soon.

**Comment by vsimon** [comment]
Friendly ping, any review update? This PR contains some very useful contributions and fixes.

**Comment by vsimon** [comment]
Hi, thanks for the update! I'm not the original contributor but I think that sounds reasonable! 😄

**Comment by vsimon** [comment]
Hi there! Quick question, for time, would it be possible to prioritize and cherry-pick just one of these fixes from this PR: https://github.com/sipwise/janus-client/pull/8/commits/7235d8f6dde6f5ba3d71dd84b0ff40bd2a645862

I don't think this would break compatibility against an older Janus version as the mandary field that is missing is documented in the Janus API.

Thanks.

**Comment by cedbale** [comment]
@hpherzog sounds good

**Comment by hpherzog** [comment]
> Hi there @hpherzog! Quick question, for time, would it be possible to prioritize and cherry-pick just one of these fixes from this PR: [7235d8f](https://github.com/sipwise/janus-client/commit/7235d8f6dde6f5ba3d71dd84b0ff40bd2a645862)
> 
> I don't think this would break compatibility against an older Janus version as the mandatory field that is missing is documented in the Janus API.
> 
> Thanks.

Done. Release 3.2.8 including the requested commit [7235d8f] is available.

https://www.npmjs.com/package/janus-videoroom-client

**Comment by vsimon** [comment]
Thank you!

**Pull request closed without merging**
